# Generated by Django 5.0.7 on 2024-07-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=256)),
            ],
        ),
    ]
